# -*- coding: utf-8 -*-
"""CNN_fusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177fmggeKJOVXhTZ0_mvPJZlZiNVQFM1r
"""

!pip install kaggle

from google.colab import files
files.upload()

!unzip CT-MRI.zip
import os
os.listdir("/content/CT-MRI")

# --------------------------
# Step 0: Imports
# --------------------------
import time
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

# --------------------------
# Step 1: Device
# --------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# --------------------------
# Step 2: Load image
# --------------------------
def load_image(path):
    img = Image.open(path).convert("L")   # grayscale
    img = np.array(img).astype(np.float32) / 255.0
    return img

# --------------------------
# Step 3: CNN Feature Extractor
# --------------------------
class CNNBranch(nn.Module):
    def __init__(self, out_channels=32):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 16, 3, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, out_channels, 3, padding=1),
            nn.ReLU()
        )

    def forward(self, x):
        return self.features(x)

# --------------------------
# Step 4: Fusion Module (CNN only)
# --------------------------
class CNNFusion(nn.Module):
    def __init__(self, channels=32):
        super().__init__()
        self.fuse = nn.Conv2d(channels * 2, channels, 1)

    def forward(self, f_ct, f_mri):
        fused = torch.cat([f_ct, f_mri], dim=1)
        fused = self.fuse(fused)
        return fused

# --------------------------
# Step 5: Dataset paths
# --------------------------
ct_dir = "/content/CT-MRI/CT"
mri_dir = "/content/CT-MRI/MRI"

ct_images = sorted([f for f in os.listdir(ct_dir) if f.endswith(".png")])
mri_images = sorted([f for f in os.listdir(mri_dir) if f.endswith(".png")])

num_images = min(10, len(ct_images), len(mri_images))

# --------------------------
# Step 6: Initialize model
# --------------------------
cnn = CNNBranch().to(device)
fusion = CNNFusion().to(device)

# --------------------------
# Step 7: Run Fusion
# --------------------------
start_time = time.time()
plt.figure(figsize=(15, 20))

for i in range(num_images):

    ct_path = os.path.join(ct_dir, ct_images[i])
    mri_path = os.path.join(mri_dir, mri_images[i])

    ct = load_image(ct_path)
    mri = load_image(mri_path)

    ct_t = torch.tensor(ct).unsqueeze(0).unsqueeze(0).to(device)
    mri_t = torch.tensor(mri).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        f_ct = cnn(ct_t)
        f_mri = cnn(mri_t)
        fused_feat = fusion(f_ct, f_mri)
        fused = fused_feat.mean(dim=1).squeeze().cpu().numpy()

    # --------------------------
    # Display
    # --------------------------
    plt.subplot(num_images, 3, i*3 + 1)
    plt.imshow(ct, cmap="gray")
    plt.title(f"CT\n{ct_images[i]}")
    plt.axis("off")

    plt.subplot(num_images, 3, i*3 + 2)
    plt.imshow(mri, cmap="gray")
    plt.title(f"MRI\n{mri_images[i]}")
    plt.axis("off")

    plt.subplot(num_images, 3, i*3 + 3)
    plt.imshow(fused, cmap="gray")
    plt.title("Fused (CNN only)")
    plt.axis("off")

plt.tight_layout()
plt.show()

end_time = time.time()
print("Execution Time:", round(end_time - start_time, 2), "seconds")

total_images = min(len(ct_images), len(mri_images))
start_index = int(0.8 * total_images)
end_index = total_images

num_images = end_index - start_index

plt.figure(figsize=(15, 4*num_images))

for idx, i in enumerate(range(start_index, end_index)):

    ct_path = os.path.join(ct_dir, ct_images[i])
    mri_path = os.path.join(mri_dir, mri_images[i])

    ct = load_image(ct_path)
    mri = load_image(mri_path)

    ct_t = torch.tensor(ct).unsqueeze(0).unsqueeze(0).to(device)
    mri_t = torch.tensor(mri).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        f_ct = cnn(ct_t)
        f_mri = cnn(mri_t)
        fused_feat = fusion(f_ct, f_mri)
        fused = fused_feat.mean(dim=1).squeeze().cpu().numpy()

    plt.subplot(num_images, 3, idx*3 + 1)
    plt.imshow(ct, cmap="gray")
    plt.title("CT (Test)")
    plt.axis("off")

    plt.subplot(num_images, 3, idx*3 + 2)
    plt.imshow(mri, cmap="gray")
    plt.title("MRI (Test)")
    plt.axis("off")

    plt.subplot(num_images, 3, idx*3 + 3)
    plt.imshow(fused, cmap="gray")
    plt.title("Fused (CNN only)")
    plt.axis("off")

plt.tight_layout()
plt.show()

from skimage.metrics import structural_similarity as ssim
from math import log10
import pandas as pd

def entropy(img):
    hist, _ = np.histogram(img.flatten(), bins=256, range=(0,1))
    hist = hist / (hist.sum() + 1e-10)
    return -np.sum(hist * np.log2(hist + 1e-10))

def psnr(img1, img2):
    mse = np.mean((img1 - img2) ** 2)
    if mse == 0:
        return 100
    return 20 * log10(1.0 / np.sqrt(mse))

def rmse(img1, img2):
    return np.sqrt(np.mean((img1 - img2) ** 2))

def mutual_information(x, y):
    hist_2d, _, _ = np.histogram2d(
        x.flatten(), y.flatten(), bins=64, range=[[0,1],[0,1]]
    )
    pxy = hist_2d / np.sum(hist_2d)
    px = np.sum(pxy, axis=1)
    py = np.sum(pxy, axis=0)
    px_py = px[:, None] * py[None, :]
    return np.sum(pxy * np.log2((pxy + 1e-10) / (px_py + 1e-10)))

metrics_data = []

for i in range(num_images):

    ct_path = os.path.join(ct_dir, ct_images[i])
    mri_path = os.path.join(mri_dir, mri_images[i])

    ct = load_image(ct_path)
    mri = load_image(mri_path)

    ct_t = torch.tensor(ct).unsqueeze(0).unsqueeze(0).to(device)
    mri_t = torch.tensor(mri).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        f_ct = cnn(ct_t)
        f_mri = cnn(mri_t)
        fused_feat = fusion(f_ct, f_mri)
        fused = fused_feat.mean(dim=1).squeeze().cpu().numpy()

    metrics_data.append([
        ct_images[i],                     # Exact image name
        round(entropy(fused), 4),
        round(psnr(ct, fused), 4),
        round(ssim(ct, fused, data_range=1.0), 4),
        round(mutual_information(ct, fused), 4),
        round(rmse(ct, fused), 4)
    ])

# Create DataFrame
columns = ["Image Name", "Entropy", "PSNR", "SSIM", "Mutual Info", "RMSE"]
df_metrics = pd.DataFrame(metrics_data, columns=columns)

df_metrics

metrics_list = df_metrics.values.tolist()
print(metrics_list)

