# -*- coding: utf-8 -*-
"""GAN_fusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBrjVY6bVUEyBvsMtzpLHeAZdYKUCk7G
"""

import os
import time
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

!pip install kaggle

from google.colab import files
files.upload()

!unzip CT-MRI.zip

os.listdir("/content/CT-MRI")

!pip install torch torchvision pytorch-msssim

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import numpy as np
from pytorch_msssim import ssim

class CTMRIDataset(Dataset):
    def __init__(self, ct_dir, mri_dir):
        self.ct_dir = ct_dir
        self.mri_dir = mri_dir
        self.ct_imgs = sorted(os.listdir(ct_dir))
        self.mri_imgs = sorted(os.listdir(mri_dir))

        self.transform = transforms.Compose([
            transforms.Resize((256,256)),
            transforms.ToTensor()
        ])

    def __len__(self):
        return min(len(self.ct_imgs), len(self.mri_imgs))

    def __getitem__(self, idx):
        ct = Image.open(os.path.join(self.ct_dir, self.ct_imgs[idx])).convert("L")
        mri = Image.open(os.path.join(self.mri_dir, self.mri_imgs[idx])).convert("L")

        ct = self.transform(ct)
        mri = self.transform(mri)

        return ct, mri

dataset = CTMRIDataset("/content/CT-MRI/CT", "/content/CT-MRI/MRI")
loader = DataLoader(dataset, batch_size=4, shuffle=True)

class ResBlock(nn.Module):
    def __init__(self, ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(ch, ch, 3, 1, 1),
            nn.BatchNorm2d(ch),
            nn.LeakyReLU(0.2),
            nn.Conv2d(ch, ch, 3, 1, 1),
            nn.BatchNorm2d(ch)
        )

    def forward(self, x):
        return x + self.block(x)

class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.enc = nn.Sequential(
            nn.Conv2d(2, 64, 3, 1, 1),
            nn.LeakyReLU(0.2),
            ResBlock(64),
            ResBlock(64)
        )

        self.dec = nn.Sequential(
            nn.Conv2d(64, 1, 3, 1, 1),
            nn.Tanh()
        )

    def forward(self, ct, mri):
        x = torch.cat([ct, mri], dim=1)
        x = self.enc(x)
        return self.dec(x)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Conv2d(2, 64, 4, 2, 1),
            nn.LeakyReLU(0.2),

            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2),

            nn.Conv2d(128, 1, 4, 1, 1)
        )

    def forward(self, x):
        return self.model(x)

def gradient_loss(fused, mri):
    fx = fused[:, :, :, 1:] - fused[:, :, :, :-1]
    fy = fused[:, :, 1:, :] - fused[:, :, :-1, :]
    mx = mri[:, :, :, 1:] - mri[:, :, :, :-1]
    my = mri[:, :, 1:, :] - mri[:, :, :-1, :]
    return torch.mean(torch.abs(fx - mx)) + torch.mean(torch.abs(fy - my))

def ssim_loss(fused, mri):
    return 1 - ssim(fused, mri, data_range=1.0)

vgg = models.vgg16(pretrained=True).features[:16].to(device)
for p in vgg.parameters():
    p.requires_grad = False

def perceptual_loss(fused, ct):
    fused_rgb = fused.repeat(1,3,1,1)
    ct_rgb = ct.repeat(1,3,1,1)
    return torch.mean((vgg(fused_rgb) - vgg(ct_rgb))**2)

G = Generator().to(device)
D = Discriminator().to(device)

opt_G = optim.Adam(G.parameters(), lr=2e-4)
opt_D = optim.Adam(D.parameters(), lr=2e-4)

bce = nn.BCEWithLogitsLoss()
l1 = nn.L1Loss()

epochs = 10

for epoch in range(epochs):
    for ct, mri in loader:
        ct, mri = ct.to(device), mri.to(device)

        # ---------------------
        # Train Discriminator
        # ---------------------
        fused = G(ct, mri)

        real_ct = D(torch.cat([ct, ct], dim=1))
        real_mri = D(torch.cat([mri, mri], dim=1))
        fake_ct = D(torch.cat([fused.detach(), ct], dim=1))
        fake_mri = D(torch.cat([fused.detach(), mri], dim=1))

        d_loss = (
            bce(real_ct, torch.ones_like(real_ct)) +
            bce(real_mri, torch.ones_like(real_mri)) +
            bce(fake_ct, torch.zeros_like(fake_ct)) +
            bce(fake_mri, torch.zeros_like(fake_mri))
        ) * 0.5

        opt_D.zero_grad()
        d_loss.backward()
        opt_D.step()

        # ---------------------
        # Train Generator
        # ---------------------
        adv_loss = (
            bce(D(torch.cat([fused, ct], dim=1)), torch.ones_like(fake_ct)) +
            bce(D(torch.cat([fused, mri], dim=1)), torch.ones_like(fake_mri))
        ) * 0.5

        g_loss = (
            adv_loss +
            l1(fused, ct) +
            gradient_loss(fused, mri) +
            ssim_loss(fused, mri) +
            perceptual_loss(fused, ct)
        )

        opt_G.zero_grad()
        g_loss.backward()
        opt_G.step()

    print(f"Epoch [{epoch+1}/{epochs}] | D Loss: {d_loss.item():.4f} | G Loss: {g_loss.item():.4f}")

torch.save(G.state_dict(), "MedFusionGAN_Generator.pth")

G = Generator().to(device)
G.load_state_dict(torch.load("MedFusionGAN_Generator.pth", map_location=device))
G.eval()

# ---------------------------------------------------
# GAN QUALITATIVE RESULTS (SAME IMAGES AS PROPOSED)
# ---------------------------------------------------

ct_dir = "/content/CT-MRI/CT"
mri_dir = "/content/CT-MRI/MRI"

ct_images = sorted([f for f in os.listdir(ct_dir) if f.endswith(".png")])
mri_images = sorted([f for f in os.listdir(mri_dir) if f.endswith(".png")])

num_images = 10
plt.figure(figsize=(15, 20))

G.eval()

for i in range(num_images):

    ct_path = os.path.join(ct_dir, ct_images[i])
    mri_path = os.path.join(mri_dir, mri_images[i])

    ct = Image.open(ct_path).convert("L").resize((256,256))
    mri = Image.open(mri_path).convert("L").resize((256,256))

    ct_np = np.array(ct).astype(np.float32) / 255.0
    mri_np = np.array(mri).astype(np.float32) / 255.0

    ct_t = torch.tensor(ct_np).unsqueeze(0).unsqueeze(0).to(device)
    mri_t = torch.tensor(mri_np).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        fused = G(ct_t, mri_t)

    fused_img = fused.squeeze().cpu().numpy()

    fused_img = (fused_img + 1) / 2
    fused_img = np.clip(fused_img, 0, 1)

    plt.subplot(num_images, 3, i*3 + 1)
    plt.imshow(ct_np, cmap='gray')
    plt.title(f"CT\n{ct_images[i]}")
    plt.axis("off")

    plt.subplot(num_images, 3, i*3 + 2)
    plt.imshow(mri_np, cmap='gray')
    plt.title(f"MRI\n{mri_images[i]}")
    plt.axis("off")

    plt.subplot(num_images, 3, i*3 + 3)
    plt.imshow(fused_img, cmap='gray')
    plt.title("Fused (GAN)")
    plt.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

num_images = 10

plt.figure(figsize=(15, 20))

with torch.no_grad():
    for i, (ct, mri) in enumerate(loader):
        if i >= num_images:
            break

        ct = ct.to(device)
        mri = mri.to(device)

        fused = G(ct, mri)

        ct_img = ct[0].squeeze().cpu().numpy()
        mri_img = mri[0].squeeze().cpu().numpy()
        fused_img = fused[0].squeeze().cpu().numpy()

        # --------------------------
        # Plot
        # --------------------------
        plt.subplot(num_images, 3, i*3 + 1)
        plt.imshow(ct_img, cmap="gray")
        plt.title("CT")
        plt.axis("off")

        plt.subplot(num_images, 3, i*3 + 2)
        plt.imshow(mri_img, cmap="gray")
        plt.title("MRI")
        plt.axis("off")

        plt.subplot(num_images, 3, i*3 + 3)
        plt.imshow(fused_img, cmap="gray")
        plt.title("Fused (GAN)")
        plt.axis("off")

plt.tight_layout()
plt.show()

# =========================================================
# GAN EVALUATION CODE (Entropy, PSNR, SSIM, MI, RMSE)
# Images: 16003 – 16012
# =========================================================

import os
import numpy as np
import pandas as pd
from PIL import Image
from math import log10
from skimage.metrics import structural_similarity as ssim

# --------------------------
# Paths
# --------------------------
ct_dir = "/content/CT-MRI/CT"
mri_dir = "/content/CT-MRI/MRI"

ct_images = sorted([f for f in os.listdir(ct_dir) if f.endswith(".png")])
mri_images = sorted([f for f in os.listdir(mri_dir) if f.endswith(".png")])

# --------------------------
# Image loader (GAN compatible)
# --------------------------
def load_image(path):
    img = Image.open(path).convert("L")
    img = img.resize((256, 256))
    img = np.array(img).astype(np.float32) / 255.0
    return img

# --------------------------
# Metrics
# --------------------------
def entropy(img):
    hist, _ = np.histogram(img.flatten(), bins=256, range=(0, 1))
    hist = hist / (hist.sum() + 1e-10)
    return -np.sum(hist * np.log2(hist + 1e-10))

def psnr(img1, img2):
    mse = np.mean((img1 - img2) ** 2)
    if mse == 0:
        return 100
    return 20 * log10(1.0 / np.sqrt(mse))

def rmse(img1, img2):
    return np.sqrt(np.mean((img1 - img2) ** 2))

def mutual_information(x, y):
    hist_2d, _, _ = np.histogram2d(
        x.flatten(), y.flatten(), bins=64, range=[[0,1],[0,1]]
    )
    pxy = hist_2d / np.sum(hist_2d)
    px = np.sum(pxy, axis=1)
    py = np.sum(pxy, axis=0)
    px_py = px[:, None] * py[None, :]
    return np.sum(pxy * np.log2((pxy + 1e-10) / (px_py + 1e-10)))

# --------------------------
# GAN Evaluation
# --------------------------
metrics_data = []
G.eval()

for i in range(10):  # images 16003–16012
    ct_path = os.path.join(ct_dir, ct_images[i])
    mri_path = os.path.join(mri_dir, mri_images[i])

    ct = load_image(ct_path)
    mri = load_image(mri_path)

    ct_t = torch.tensor(ct).unsqueeze(0).unsqueeze(0).to(device)
    mri_t = torch.tensor(mri).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        fused = G(ct_t, mri_t).squeeze().cpu().numpy()

    # Normalize GAN output (Tanh → [0,1])
    fused = (fused + 1) / 2
    fused = np.clip(fused, 0, 1)

    metrics_data.append([
        ct_images[i],
        entropy(fused),
        psnr(fused, ct),
        ssim(fused, ct, data_range=1.0),
        mutual_information(fused, ct),
        rmse(fused, ct)
    ])

# --------------------------
# Results Table
# --------------------------
df_gan = pd.DataFrame(
    metrics_data,
    columns=["Image Name", "Entropy", "PSNR", "SSIM", "Mutual Info", "RMSE"]
)

df_gan



metrics_list = df_gan.values.tolist()
print(metrics_list)









import os
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

class FusionDataset(Dataset):
    def __init__(self, ct_dir, mri_dir):
        self.ct_dir = ct_dir
        self.mri_dir = mri_dir

        self.ct_images = sorted(os.listdir(ct_dir))
        self.mri_images = sorted(os.listdir(mri_dir))

        self.transform = transforms.Compose([
            transforms.Resize((256, 256)),
            transforms.ToTensor(),
            transforms.Normalize((0.5,), (0.5,))  # Normalize to [-1,1]
        ])

    def __len__(self):
        return len(self.ct_images)

    def __getitem__(self, idx):
        ct_path = os.path.join(self.ct_dir, self.ct_images[idx])
        mri_path = os.path.join(self.mri_dir, self.mri_images[idx])

        ct = Image.open(ct_path).convert("L")
        mri = Image.open(mri_path).convert("L")

        ct = self.transform(ct)
        mri = self.transform(mri)

        return ct, mri

class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()

        self.model = nn.Sequential(
            nn.Conv2d(2, 64, 3, 1, 1),
            nn.ReLU(True),

            nn.Conv2d(64, 128, 3, 1, 1),
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            nn.Conv2d(128, 64, 3, 1, 1),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            nn.Conv2d(64, 1, 3, 1, 1),
            nn.Tanh()
        )

    def forward(self, ct, mri):
        x = torch.cat([ct, mri], dim=1)
        return self.model(x)

class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()

        self.model = nn.Sequential(
            nn.Conv2d(1, 64, 4, 2, 1),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(64, 128, 4, 2, 1),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(128, 1, 4, 1, 1)
        )

    def forward(self, x):
        return self.model(x)

adversarial_loss = nn.BCEWithLogitsLoss()
l1_loss = nn.L1Loss()

def gradient_loss(fused, target):
    fx = fused[:, :, :, :-1] - fused[:, :, :, 1:]
    fy = fused[:, :, :-1, :] - fused[:, :, 1:, :]

    tx = target[:, :, :, :-1] - target[:, :, :, 1:]
    ty = target[:, :, :-1, :] - target[:, :, 1:, :]

    return l1_loss(fx, tx) + l1_loss(fy, ty)

dataset = FusionDataset("/content/CT-MRI/CT", "/content/CT-MRI/MRI")
loader = DataLoader(dataset, batch_size=4, shuffle=True)

G = Generator().to(device)
D = Discriminator().to(device)

optimizer_G = optim.Adam(G.parameters(), lr=0.0002, betas=(0.5, 0.999))
optimizer_D = optim.Adam(D.parameters(), lr=0.0002, betas=(0.5, 0.999))

epochs = 100

for epoch in range(epochs):
    for ct, mri in loader:

        ct = ct.to(device)
        mri = mri.to(device)

        # --------------------
        # Train Generator
        # --------------------
        optimizer_G.zero_grad()

        fused = G(ct, mri)
        pred_fake = D(fused)

        real = torch.ones_like(pred_fake)
        fake = torch.zeros_like(pred_fake)

        adv_loss = adversarial_loss(pred_fake, real)

        l1_ct = l1_loss(fused, ct)
        l1_mri = l1_loss(fused, mri)

        grad_mri = gradient_loss(fused, mri)

        g_loss = (
            1.0 * adv_loss +
            5.0 * l1_ct +
            5.0 * l1_mri +
            2.0 * grad_mri
        )

        g_loss.backward()
        optimizer_G.step()

        # --------------------
        # Train Discriminator
        # --------------------
        optimizer_D.zero_grad()

        real_loss = adversarial_loss(D(ct), real)
        fake_loss = adversarial_loss(D(fused.detach()), fake)

        d_loss = (real_loss + fake_loss) / 2

        d_loss.backward()
        optimizer_D.step()

    print(f"Epoch [{epoch+1}/{epochs}]  G_loss: {g_loss.item():.4f}  D_loss: {d_loss.item():.4f}")

# ---------------------------------------------------
# GAN QUALITATIVE RESULTS (SAME IMAGES AS PROPOSED)
# ---------------------------------------------------

ct_dir = "/content/CT-MRI/CT"
mri_dir = "/content/CT-MRI/MRI"

ct_images = sorted([f for f in os.listdir(ct_dir) if f.endswith(".png")])
mri_images = sorted([f for f in os.listdir(mri_dir) if f.endswith(".png")])

num_images = 10
plt.figure(figsize=(15, 20))

G.eval()

for i in range(num_images):

    ct_path = os.path.join(ct_dir, ct_images[i])
    mri_path = os.path.join(mri_dir, mri_images[i])

    ct = Image.open(ct_path).convert("L").resize((256,256))
    mri = Image.open(mri_path).convert("L").resize((256,256))

    ct_np = np.array(ct).astype(np.float32) / 255.0
    mri_np = np.array(mri).astype(np.float32) / 255.0

    ct_t = torch.tensor(ct_np).unsqueeze(0).unsqueeze(0).to(device)
    mri_t = torch.tensor(mri_np).unsqueeze(0).unsqueeze(0).to(device)

    with torch.no_grad():
        fused = G(ct_t, mri_t)

    fused_img = fused.squeeze().cpu().numpy()

    fused_img = (fused_img + 1) / 2
    fused_img = np.clip(fused_img, 0, 1)

    plt.subplot(num_images, 3, i*3 + 1)
    plt.imshow(ct_np, cmap='gray')
    plt.title(f"CT\n{ct_images[i]}")
    plt.axis("off")

    plt.subplot(num_images, 3, i*3 + 2)
    plt.imshow(mri_np, cmap='gray')
    plt.title(f"MRI\n{mri_images[i]}")
    plt.axis("off")

    plt.subplot(num_images, 3, i*3 + 3)
    plt.imshow(fused_img, cmap='gray')
    plt.title("Fused (GAN)")
    plt.axis("off")

plt.tight_layout()
plt.show()

